### ISSUE TITLE
installing error: undefined symbol: zgesv_

### ISSUE THREAD

**Issue by zltemp** [hungpham2017/pyWannier90#10]
Dear Contributor:

Recently I am trying to install the pywannier90. After I compile the libwannier90, I obtained 2 files, naming as "libwannier90.cpp" and "libwannier90.cpython-37m-x86_64-linux-gnu.so".
But after I move the .so file to /pbc/tools and try [python3 -c "import libwannier90"], I obtain the following error:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: [my own directory]/python3.8/site-packages/pyscf/pbc/tools/libwannier90.cpython-37m-x86_64-linux-gnu.so: undefined symbol: zgesv_

So is there a compiling error? 
I also want to know that, as you mentioned in /pyscf/pbc/tools/pywannier90.py that:
['WARNING: Check the installation of libwannier90 and its path in pyscf/pbc/tools/pywannier90.py']
But actually, I did not find the code that related to the path of libwannier90 in the .py code. Instead, I found in /pyWannier90/src/pywannier90.py that:
[W90LIB = '/burg/home/hqp2000/pyWannier90/src']
I tries changing this line to the related directory, and copy this line to pyscf/pbc/tools/pywannier90.py. Both of my attempts do not work. So is this line necessary in pyscf/pbc/tools/pywannier90.py?

Thank you for reading this and looking forward to your reply.

**Comment by fanunez5** [comment]
Hello dear contributor and zltemp, I wanted to know if you could solve the problem because I am trying to install and I get the same error:

installing error: undefined symbol: zgesv_

I don't know if the contributor or you could help me.

thank,  I remain attentive to your answers

Greetings.

**Comment by simonganne01** [comment]
I have the same problem.

**Comment by zltemp** [comment]
Hi all. I finally made it work. 
So I tried using the Intel compiler and made the necessary changes to the make file. I also changed the directory paths in the makefile, which are [W90DIR =[somewhere]/wannier90-3.1.0; LIBDIR =[somewhere to your compiler library]]. Finally, I moved the libwannier90.cpython-37m-x86_64-linux-gnu.so file to the directory I run my pyscf jobs. 
Hope this will help.

**Comment by simonganne01** [comment]
Can you give more info on which folder the LIBDIR should be?

**Comment by zltemp** [comment]
LIBDIR =[somewhere to your compiler library]
It should be your library of Intel compiler, something like /opt/intel. You need to check the one on your own server.

**Comment by tsevasa** [comment]
I use WSL and had exactly the same issue, even after correctly setting LIBDIR. Force-loading the lapack library solved it for me:
```export LD_PRELOAD=/path/to/your/liblapack.so```
(as pointed out by [hungpham2017](https://github.com/hungpham2017) in #11 )
