### ISSUE TITLE
Problem with installing 

### ISSUE THREAD

**Issue by simonganne01** [hungpham2017/pyWannier90#11]
Hello, 

I get the following error message when installing (when executing the last step): 
Traceback (most recent call last):

  File "<string>", line 1, in <module>
ImportError: /home/sganne/Thesis/pyWannier90/src/libwannier90.cpython-310-x86_64-linux-gnu.so: undefined symbol: __w90lib_MOD_wannier_run

this is the result when I use the nm command on the libwanier90.cpython-... file:
[nm.txt](https://github.com/hungpham2017/pyWannier90/files/13517249/nm.txt)

this the result when i use the nm command with the libwannier.a file:
[nm_libwannier90.txt](https://github.com/hungpham2017/pyWannier90/files/13517274/nm_libwannier90.txt)

Any idea what it could be?

**Comment by simonganne01** [comment]
I found a relatable issue, but the solution didn't solve my problem: 

objdump -t  wannier_lib.o | grep w90lib_
0000000000000000 g     F .text  0000000000000108 __w90lib_MOD_element_dict
0000000000000110 g     F .text  000000000000000b __w90lib_MOD_pass_boolean
0000000000000120 g     F .text  00000000000031de __w90lib_MOD_wannier_run
0000000000003300 g     F .text  0000000000001c21  #__w90lib_MOD_wannier_setup

#2

**Comment by hungpham2017** [comment]
Look like you have similar problem like this issue #2, have you had a look?

**Comment by simonganne01** [comment]
Yes, but I followed the instructions in yournreadme and the result of the test in issue #2 is the following: 

objdump -t wannier_lib.o | grep w90lib_
0000000000000000 g F .text 0000000000000108 __w90lib_MOD_element_dict
0000000000000110 g F .text 000000000000000b __w90lib_MOD_pass_boolean
0000000000000120 g F .text 00000000000031de __w90lib_MOD_wannier_run
0000000000003300 g F .text 0000000000001c21 #__w90lib_MOD_wannier_setup

So it seems normal to me. But the symbol is still undefined (U) in the .so file

**Comment by hungpham2017** [comment]
That is a bit strange. Do you find **libwannier.a** under the root directory of wannier90-X.X.X?

**Comment by simonganne01** [comment]
Yes and I also checked that the function is defined there. 

nm libwannier.a | grep w90lib_
0000000000000000 T __w90lib_MOD_element_dict
0000000000000110 T __w90lib_MOD_pass_boolean
0000000000000120 T __w90lib_MOD_wannier_run
0000000000003300 T __w90lib_MOD_wannier_setup

this is from the makefile of PyWannier90:
W90DIR =/home/sganne/Thesis/wannier90-3.1.0/
LIBDIR = /usr/lib/x86_64-linux-gnu/
USE_INTEL = no 

I think those are the correct directories, the compilation itself is succesfull. Its when I import the library that I get an error.

**Comment by daanverraes** [comment]
Hi,

Is this issue solved yet? Because I receive the same error messages while installing...

Thanks in advance!

**Comment by simonganne01** [comment]
Is there any improvement with this issue?

**Comment by hungpham2017** [comment]
> Is there any improvement with this issue?

@simonganne01  I am in the process of packaging the project and put it on PyPi to simplify the installation. Hopefully, by the end of next week. In the meantime, I suggest that you can try to install libwannier90 library following this:

**Note**: No separate wannier90 installation is needed.

**on Linux**:
`git clone https://github.com/hungpham2017/libwannier90.git`
`cd libwannier90`
`pip install .`


**on mac**:
`pip install libwannier90`

The wrapper pywannier90.py (via PySCF or [mcu](https://github.com/hungpham2017/mcu) ) should see this library so no need to set any path in pywannier90.py

Try `import libwannier90` to see if it works, you should see no error. On Linux, if you run into problem like `undefined symbol: zgesv_`, you can force load the lapack library:

`export LD_PRELOAD=/path/to/your/liblapack.so`

Let me know if this works

**Comment by simonganne01** [comment]
It seems to be installed since the "import libwannier90" does not raise an error. But I get the following further down the line: AttributeError: module 'libwannier90' has no attribute 'setup'

any ideas?

**Comment by hungpham2017** [comment]
> It seems to be installed since the "import libwannier90" does not raise an error. But I get the following further down the line: AttributeError: module 'libwannier90' has no attribute 'setup'
> 
> any ideas?

This likely indicates the library wasn't really installed. Maybe you executed the "import libwannier90" command in some directory that has the libwannier90 folder. If you go under libwannier90 directory and look into the build folder, you should find the library *.so file

can you share the output of "pip install ."

**Comment by simonganne01** [comment]
this is the output of pip install: 
"""
Processing /home/sganne/libwannier90-main
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pybind11>=2.6.0 in /usr/local/lib/python3.10/dist-packages (from libwannier90==0.2.1) (2.11.1)
Building wheels for collected packages: libwannier90
  Building wheel for libwannier90 (setup.py) ... done
  Created wheel for libwannier90: filename=libwannier90-0.2.1-cp310-cp310-linux_x86_64.whl size=1696899 sha256=b27bbf42da729c7dc57884ab4abb618840c5aa46c0ad4ab5f9aa6e6a8b20f626
  Stored in directory: /root/.cache/pip/wheels/cf/1c/b8/737de5de6ecf9c78bedb077c71901b67575c78ba0e9a78c038
Successfully built libwannier90
Installing collected packages: libwannier90
  Attempting uninstall: libwannier90
    Found existing installation: libwannier90 0.2.1
    Uninstalling libwannier90-0.2.1:
      Successfully uninstalled libwannier90-0.2.1
Successfully installed libwannier90-0.2.1
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
"""

And its indeed the case that if I change folders and try to import ibwannier90 in a different folder, it does not recognize the library although it seems to be installed according to the pip output. I also found the *.so file

**Comment by simonganne01** [comment]
I finally succeeded! Thanks for your help. This worked when I tried it for a second time on an new ubuntu subsystem. 

> > Is there any improvement with this issue?
> 
> @simonganne01 I am in the process of packaging the project and put it on PyPi to simplify the installation. Hopefully, by the end of next week. In the meantime, I suggest that you can try to install libwannier90 library following this:
> 
> **Note**: No separate wannier90 installation is needed.
> 
> **on Linux**: `git clone https://github.com/hungpham2017/libwannier90.git` `cd libwannier90` `pip install .`
> 
> **on mac**: `pip install libwannier90`
> 
> The wrapper pywannier90.py (via PySCF or [mcu](https://github.com/hungpham2017/mcu) ) should see this library so no need to set any path in pywannier90.py
> 
> Try `import libwannier90` to see if it works, you should see no error. On Linux, if you run into problem like `undefined symbol: zgesv_`, you can force load the lapack library:
> 
> `export LD_PRELOAD=/path/to/your/liblapack.so`
> 
> Let me know if this works
