### ISSUE TITLE
Error: Problem reading keyword num_wann

### ISSUE THREAD

**Issue by bbusemeyer** [hungpham2017/pyWannier90#5]
I cannot run the examples in the PySCF nor the pyWannier90 repositories, both giving the same error:
```
You are running Wannier90_setup via pyWannier90
 Error: Problem reading keyword num_wann
Error: examine the output/error file for details
```

I'll focus on the example in pyscf/pbc/tools/pywannier90.py
The input file for wannier90 is produced successfully and looks fine to me:
```
! Basic input

num_bands       = 9
num_wann       = 4

Begin Unit_Cell_Cart
 6.3500000   0.0000000   0.0000000
 0.0000000   6.3500000   0.0000000
 0.0000000   0.0000000   6.3500000
End Unit_Cell_Cart

Begin atoms_cart
C  3.1750000  3.1750000  3.1750000
H  2.5462656  2.5462656  2.5462656
H  3.8037344  3.8037344  2.5462656
H  2.5462656  3.8037344  3.8037344
H  3.8037344  2.5462656  3.8037344
End atoms_cart

!Additional keywords

    exclude_bands : 1,6-9
    begin projections
    C:sp3
    end projections
    


mp_grid        = 1 1 1
begin kpoints
0.0000000  0.0000000  0.0000000
End Kpoints
```

The output prints, after some headers, 
``` 
Wannier90 is running in LIBRARY MODE via pyWannier90

 Setting up k-point neighbours...

 Exiting.......
 Error: Problem reading keyword num_wann
```
I am running pywannier90.py on a Linux cluster, and I compiled using GNU compilers, and also followed instructions in https://github.com/hungpham2017/pyWannier90/issues/4#issuecomment-631853143

**Comment by hungpham2017** [comment]
Oops, I just saw this issue now. Sorry for the late response.
I just submitted a pull request for the new version of pywannier90.py as well as an example in the pyscf/example/47-pywannier90.py.
I am not sure when it will be merged to the dev branch. In the meantime, I can send you these two files via email.
If this works for you, please let me know your email.

**Comment by bbusemeyer** [comment]
No worries! I found [your PR](https://github.com/pyscf/pyscf/pull/647#issue-441540234), I can just use the changes there. I'll check tomorrow if it fixed the problem. Thanks!

**Comment by hungpham2017** [comment]
Great! I close this issue for now. Please let me know if there is any other problem.
