### ISSUE TITLE
Wannierization with Pseudopotentials 

### ISSUE THREAD

**Issue by vamshimohank** [hungpham2017/pyWannier90#6]
Hi,

Thanks for implementing Wannierization for PySCF. I was wondering if your implementation also works when pseudopotentials are used?

Regards
Vamshi

**Comment by hungpham2017** [comment]
Yes, there should be no problem. In PySCF, the core contribution via the pseudopotential (pp) is included in the core Hamiltonian, i.e., hcore = kin + nuc-el + pp. The pyWannier90 implementation uses the (valence or all-electrons) wave function that is spaned by the periodic Gaussians. Hence, there is no difference in the implementation between all-electron and PP calculations.

**Comment by hungpham2017** [comment]
if there is more discussion. I closed this issue for now
