### ISSUE TITLE
undefined symbol: _gfortran_transfer_complex

### ISSUE THREAD

**Issue by conodipaola** [hungpham2017/pyWannier90#8]
Dear developer, first of all thanks a lot for the effort to share this useful tool

Unfortunately I have the following issue:

My system:
1) System Ubuntu18.04
2) gfortran7 + gcc7
3) blas and lapack libs installed with apt

wannier90 lib without wannier_lib.F90 from pywannier90 working by testing with resident tool.

after changing wannier_lib.F90 as suggested in pywannier90 installation guide:
1) modified Makefile pywannier90 as per the file attached here 'Makefile.txt'
2) after checking with the command: ' python -c "import libwannier90" ' I received the following error: 
"ImportError: /home/PYWANNIER90/pyWannier90/src/libwannier90.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _gfortran_transfer_complex"

3) to check symbols in the libwannier90 I did 'nm libwannier90.cpython-36m-x86_64-linux-gnu.so' and the result is in the file 'result.txt'

would you be so kind to let me know if you have any thoughts on this? thanks a  lot

Regards

[Makefile.txt](https://github.com/hungpham2017/pyWannier90/files/6270915/Makefile.txt)
[result.txt](https://github.com/hungpham2017/pyWannier90/files/6270917/result.txt)

**Comment by hungpham2017** [comment]
it looks to me there is a mismatch in the **lapack** library used in compiling **libwannier.a** and and libwannier90.cpython-36m-x86_64-linux-gnu.so**. Maybe you already figured that out at this point, so I closed the issue for now. Feel free to open it again if needed
